set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
set -ga update-environment TERM_PROGRAM_VERSION

set -g focus-events on
set -g default-command "${SHELL}"
set -g default-terminal "screen-256color"
set -sa terminal-overrides ",xterm-256color*:RGB"
set -g mouse on
set -g status-position top
set -s escape-time 0
set -g set-clipboard on
set -g automatic-rename off
set -g set-titles off
setw -g allow-rename on

bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-selection-and-cancel

unbind h
bind h split-window -v

unbind v
bind v split-window -h

unbind o
bind o select-pane -t :.-

unbind r
bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"

unbind T
bind T set-option -g status

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind -n M-H resize-pane -L
bind -n M-J resize-pane -D
bind -n M-K resize-pane -U
bind -n M-L resize-pane -R
