set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
run -b '~/.tmux/plugins/tpm/tpm'

source-file ~/.config/tmux/themes/catppuccin_mocha_black.tmux

set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
set -ga update-environment TERM_PROGRAM_VERSION

set -g focus-events on
set -g default-command "${SHELL}"
set -g default-terminal "screen-256color"
set -sa terminal-overrides ",xterm-256color*:RGB"
set -g mouse on
set -g status-position top
set -s escape-time 0
set -g set-clipboard on
bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-selection-and-cancel
set -g automatic-rename off
set -g set-titles off
setw -g allow-rename on

unbind h
bind h split-window -v

unbind v
bind v split-window -h

unbind o
bind o select-pane -t :.-

unbind r
bind r source-file ~/.tmux.conf

unbind T
bind T set-option -g status

bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-j select-pane -D
bind -n M-k select-pane -U

bind -n M-H resize-pane -L
bind -n M-L resize-pane -R
bind -n M-J resize-pane -D
bind -n M-K resize-pane -U

unbind -T copy-mode C-p
bind-key -n M-p copy-mode

bind p command-prompt -p "Popup command:" \
	"display-popup -E -w 90%% -h 85%% -c '#{pane_current_path}' '%%1'"

bind-key -T prefix f if-shell -F '#{==:#{pane_title},__YAZI__}' \
	'kill-pane' \
	'split-window -h -l 45% -c "#{pane_current_path}" "cd \"$(git rev-parse --show-toplevel 2>/dev/null || pwd)\" && printf \"\\033]2;__YAZI__\\033\\\\\" && yazi"'

bind-key -T prefix g if-shell -F '#{==:#{pane_title},__LAZYGIT__}' \
	'kill-pane' \
	'split-window -v -l 40% -c "#{pane_current_path}" "cd \"$(git rev-parse --show-toplevel 2>/dev/null || pwd)\" && printf \"\\033]2;__LAZYGIT__\\033\\\\\" && lazygit -ucf ~/.config/lazygit/config.yml"'

bind-key -T prefix m if-shell -F '#{==:#{pane_title},__MD__}' \
	'kill-pane' \
	'split-window -v -l 40% -c "#{pane_current_path}" "printf \"\\033]2;__MD__\\033\\\\\" && fd -e md -e markdown . | fzf --prompt=\"Markdown> \" | xargs -I{} glow -p {}"'

unbind-key -T prefix s
bind-key -T prefix s display-popup -E -w 90% -h 85% -d "$HOME" -e "CLIENT_ID=#{client_id}" \
	"bash -lc '
	  dir=\"$(zoxide query -l | fzf --prompt=\"Project (zoxide)> \")\"
	  [ -n \"$dir\" ] || exit 0

	  name=\"$(echo \"$dir\" | sed \"s#^$HOME##\" | tr \"/.\" \"__\" | sed \"s/^__//\")\"

	  if tmux has-session -t \"$name\" 2>/dev/null; then
	    tmux switch-client -c \"$CLIENT_ID\" -t \"$name\"
	    exit 0
	  fi

	  tmux new-session -d -s \"$name\" -c \"$dir\"
	  tmux send-keys -t \"$name\":0 \"hx .\" C-m
	  tmux split-window -t \"$name\":0 -h -l 40% -c \"$dir\"
	  tmux select-pane -t \"$name\":0.0

	  tmux switch-client -c \"$CLIENT_ID\" -t \"$name\"
	'"
