[settings]
experimental = true
install_before = "7d"
ruby.compile = false

[tools]
ruby = "latest"
go = "latest"
node = "lts"
java = "temurin-21"
helm-ls = "latest"
shfmt = "latest"
stylua = "latest"
yq = "latest"
